FROM eclipse-temurin:21.0.1_12-jdk-jammy

# Set the working directory in the container
WORKDIR /usr/src/app

# Install curl and unzip to download and extract dependencies
RUN apt-get update && apt-get install -y curl unzip && rm -rf /var/lib/apt/lists/*

# Download the New Relic Java agent ZIP file and extract the JAR files
RUN curl -o newrelic-java.zip https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip && \
    unzip newrelic-java.zip -d newrelic && \
    mv newrelic/newrelic/newrelic.jar ./newrelic-agent.jar && \
    mv newrelic/newrelic/newrelic-api.jar ./newrelic-api.jar && \
    rm -rf newrelic newrelic-java.zip

# Download the NanoHTTPD JAR file (replace with the correct version)
RUN curl -o nanohttpd.jar https://repo1.maven.org/maven2/org/nanohttpd/nanohttpd/2.3.1/nanohttpd-2.3.1.jar

# Download the Apache HttpClient JAR files (replace with the correct versions)
RUN curl -o httpclient.jar https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar && \
    curl -o httpcore.jar https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar && \
    curl -o commons-logging.jar https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar

# Copy the client's source code into the container
COPY src/com/newrelic/java-example /usr/src/app/com/newrelic/java-example

# Compile the Java application with the New Relic agent, New Relic API, NanoHTTPD, and Apache HttpClient on the classpath
RUN javac -cp ".:newrelic-agent.jar:newrelic-api.jar:nanohttpd.jar:httpclient.jar:httpcore.jar:commons-logging.jar" com/newrelic/java-example/NewRelicApiExample.java

# Run the client when the container launches, including the New Relic agent, New Relic API, NanoHTTPD, and Apache HttpClient on the classpath
CMD ["java", "-cp", ".:newrelic-agent.jar:newrelic-api.jar:nanohttpd.jar:httpclient.jar:httpcore.jar:commons-logging.jar", "com.newrelic.java-example.NewRelicApiExample"]
