apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-example.fullname" . }}-client-newrelic-config
  labels:
    {{- include "java-example.labels" . | nindent 4 }}
data:
  newrelic.yml: |
{{ .Files.Get "files/client-newrelic.yml" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-example.fullname" . }}-server-newrelic-config
  labels:
    {{- include "java-example.labels" . | nindent 4 }}
data:
  newrelic.yml: |
{{ .Files.Get "files/server-newrelic.yml" | indent 4 }}
